# Box.com API Credentials Configuration Example
#
# To configure Box.com integration:
#
# Option 1: Using Rails Credentials (Recommended)
# Run: rails credentials:edit
# Add the following to your credentials file:
#
# box:
#   access_token: your_box_access_token_here
#   client_id: your_box_client_id_here
#   client_secret: your_box_client_secret_here
#
# Option 2: Using Environment Variables
# Set the following environment variable:
# export BOX_ACCESS_TOKEN=your_box_access_token_here
#
# Getting Box.com API Credentials:
# 1. Go to https://developer.box.com/
# 2. Create a new app or use an existing one
# 3. Choose "Custom App" and "Server Authentication (JWT)" or "OAuth 2.0"
# 4. Get your access token from the app configuration
# 5. Ensure your app has the following scopes:
#    - Read all files and folders stored in Box
#    - Write all files and folders stored in Box
#    - Manage users
#
# For production use, consider using JWT authentication for better security
# and automatic token refresh capabilities.
#
# Note: The current implementation uses a simple access token approach.
# For production environments, implement JWT authentication for better
# security and token management.